from __future__ import annotations

import argparse
from collections import defaultdict
from io import open
import json
import math
import os
import random

import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train and evaluate a SASRec-style next-exercise recommender."
    )
    parser.add_argument(
        "--train-path",
        default="processed_sequences/train.jsonl",
        help="Exercise-level training split.",
    )
    parser.add_argument(
        "--validation-path",
        default="processed_sequences/validation.jsonl",
        help="Exercise-level validation split.",
    )
    parser.add_argument(
        "--test-path",
        default="processed_sequences/test.jsonl",
        help="Exercise-level test split.",
    )
    parser.add_argument(
        "--items-path",
        default="processed_sequences/embeddings/items.jsonl",
        help="Item catalog generated by embed_exercises.py.",
    )
    parser.add_argument(
        "--embeddings-path",
        default="processed_sequences/embeddings/item_embeddings.npz",
        help="Optional pretrained item embeddings from embed_exercises.py.",
    )
    parser.add_argument(
        "--use-pretrained-embeddings",
        action="store_true",
        help="Initialize item embeddings from semantic exercise embeddings.",
    )
    parser.add_argument(
        "--use-outcome-embedding",
        action="store_true",
        help="Add a learned outcome embedding to each exercise in the user history.",
    )
    parser.add_argument(
        "--max-len",
        type=int,
        default=50,
        help="Maximum sequence length fed into SASRec.",
    )
    parser.add_argument(
        "--hidden-dim",
        type=int,
        default=128,
        help="Hidden dimension used when not inferring from pretrained embeddings.",
    )
    parser.add_argument(
        "--num-blocks",
        type=int,
        default=2,
        help="Number of Transformer encoder blocks.",
    )
    parser.add_argument(
        "--num-heads",
        type=int,
        default=4,
        help="Number of attention heads.",
    )
    parser.add_argument(
        "--dropout",
        type=float,
        default=0.2,
        help="Dropout rate.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=128,
        help="Training batch size.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=10,
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Learning rate.",
    )
    parser.add_argument(
        "--weight-decay",
        type=float,
        default=1e-5,
        help="AdamW weight decay.",
    )
    parser.add_argument(
        "--k-values",
        default="5,10",
        help="Comma-separated evaluation cutoffs.",
    )
    parser.add_argument(
        "--early-stop-patience",
        type=int,
        default=3,
        help="Stop training after this many non-improving validation epochs. Use 0 to disable.",
    )
    parser.add_argument(
        "--monitor-metric",
        choices=["HR", "NDCG"],
        default="HR",
        help="Validation metric used for best-checkpoint selection and early stopping.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=172,
        help="Random seed.",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=0,
        help="DataLoader workers.",
    )
    parser.add_argument(
        "--device",
        default=None,
        help="Torch device, e.g. cpu or cuda. Defaults to auto-detect.",
    )
    parser.add_argument(
        "--save-dir",
        default="sasrec_artifacts",
        help="Directory for saved model checkpoints and metrics.",
    )
    return parser.parse_args()


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_jsonl(path):
    rows = []
    with open(path, "rt", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def choose_item_text(exercise):
    prompt = exercise.get("prompt")
    if prompt:
        return prompt.strip()
    return exercise["response_text"].strip()


def sort_sequence(rows):
    return sorted(
        rows,
        key=lambda row: (
            row["sort_key"][0],
            row["sort_key"][1],
            row["source_file"],
            row["source_exercise_index"],
            row["exercise_id"],
        ),
    )


def load_item_lookup(items_path):
    rows = load_jsonl(items_path)
    item_to_index = {}
    index_to_item = ["[PAD]"]
    for row in rows:
        text = row["text"]
        if text not in item_to_index:
            item_to_index[text] = len(index_to_item)
            index_to_item.append(text)
    return item_to_index, index_to_item


def load_pretrained_embeddings(embeddings_path, items_path, item_to_index):
    item_rows = load_jsonl(items_path)
    id_to_text = {row["item_id"]: row["text"] for row in item_rows}

    payload = np.load(embeddings_path)
    item_ids = payload["item_ids"]
    embeddings = payload["embeddings"].astype(np.float32)

    matrix = np.zeros((len(item_to_index) + 1, embeddings.shape[1]), dtype=np.float32)
    for item_id, embedding in zip(item_ids, embeddings):
        key = item_id.item() if hasattr(item_id, "item") else item_id
        if isinstance(key, bytes):
            key = key.decode("utf-8")
        text = id_to_text[key]
        if text in item_to_index:
            matrix[item_to_index[text]] = embedding
    return matrix


def build_split_sequences(train_rows, validation_rows, test_rows, item_to_index):
    train_by_user = defaultdict(list)
    validation_by_user = defaultdict(list)
    test_by_user = defaultdict(list)

    for row in train_rows:
        train_by_user[row["user"]].append(row)
    for row in validation_rows:
        validation_by_user[row["user"]].append(row)
    for row in test_rows:
        test_by_user[row["user"]].append(row)

    users = sorted(set(train_by_user) | set(validation_by_user) | set(test_by_user))
    train_sequences = {}
    validation_examples = []
    test_examples = []

    for user in users:
        train_sequence = sort_sequence(train_by_user.get(user, []))
        val_sequence = sort_sequence(validation_by_user.get(user, []))
        test_sequence = sort_sequence(test_by_user.get(user, []))

        train_items = [item_to_index[choose_item_text(row)] for row in train_sequence if choose_item_text(row) in item_to_index]
        train_outcomes = [int(row.get("exercise_outcome", 0) >= 0.5) for row in train_sequence if choose_item_text(row) in item_to_index]
        train_sequences[user] = {
            "items": train_items,
            "outcomes": train_outcomes,
        }

        if val_sequence:
            row = val_sequence[-1]
            item_text = choose_item_text(row)
            if item_text in item_to_index:
                validation_examples.append(
                    {
                        "user": user,
                        "history_items": train_items,
                        "history_outcomes": train_outcomes,
                        "target_item": item_to_index[item_text],
                        "target_outcome": int(row.get("exercise_outcome", 0) >= 0.5),
                    }
                )

        if test_sequence:
            row = test_sequence[-1]
            item_text = choose_item_text(row)
            if item_text in item_to_index:
                val_items = train_items[:]
                val_outcomes = train_outcomes[:]
                if val_sequence:
                    val_row = val_sequence[-1]
                    val_text = choose_item_text(val_row)
                    if val_text in item_to_index:
                        val_items = val_items + [item_to_index[val_text]]
                        val_outcomes = val_outcomes + [int(val_row.get("exercise_outcome", 0) >= 0.5)]
                test_examples.append(
                    {
                        "user": user,
                        "history_items": val_items,
                        "history_outcomes": val_outcomes,
                        "target_item": item_to_index[item_text],
                        "target_outcome": int(row.get("exercise_outcome", 0) >= 0.5),
                    }
                )

    return train_sequences, validation_examples, test_examples


class SASRecTrainDataset(Dataset):
    def __init__(self, train_sequences, max_len, num_items):
        self.examples = []
        self.max_len = max_len
        self.num_items = num_items

        for user, sequence in train_sequences.items():
            items = sequence["items"]
            outcomes = sequence["outcomes"]
            if len(items) < 2:
                continue
            self.examples.append(
                {
                    "user": user,
                    "items": items,
                    "outcomes": outcomes,
                }
            )

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        sequence = self.examples[idx]
        items = sequence["items"]
        outcomes = sequence["outcomes"]

        input_items = items[:-1][-self.max_len:]
        input_outcomes = outcomes[:-1][-self.max_len:]
        pos_targets = items[1:][-self.max_len:]

        input_items = pad_left(input_items, self.max_len, 0)
        input_outcomes = pad_left(input_outcomes, self.max_len, 0)
        pos_targets = pad_left(pos_targets, self.max_len, 0)
        neg_targets = sample_negative_targets(pos_targets, self.num_items)

        return {
            "input_items": torch.tensor(input_items, dtype=torch.long),
            "input_outcomes": torch.tensor(input_outcomes, dtype=torch.long),
            "pos_targets": torch.tensor(pos_targets, dtype=torch.long),
            "neg_targets": torch.tensor(neg_targets, dtype=torch.long),
        }


def pad_left(values, max_len, pad_value):
    if len(values) >= max_len:
        return values[-max_len:]
    return [pad_value] * (max_len - len(values)) + values


def sample_negative_targets(pos_targets, num_items):
    negatives = []
    for target in pos_targets:
        if target == 0:
            negatives.append(0)
            continue
        negative = random.randint(1, num_items)
        while negative == target:
            negative = random.randint(1, num_items)
        negatives.append(negative)
    return negatives


class SASRecModel(nn.Module):
    def __init__(
        self,
        num_items,
        hidden_dim,
        max_len,
        num_blocks,
        num_heads,
        dropout,
        pretrained_item_embeddings=None,
        use_outcome_embedding=False,
    ):
        super().__init__()
        self.num_items = num_items
        self.hidden_dim = hidden_dim
        self.max_len = max_len
        self.use_outcome_embedding = use_outcome_embedding

        self.item_embedding = nn.Embedding(num_items + 1, hidden_dim, padding_idx=0)
        if pretrained_item_embeddings is not None:
            if pretrained_item_embeddings.shape[1] != hidden_dim:
                raise ValueError("Pretrained embedding dimension does not match hidden_dim.")
            with torch.no_grad():
                self.item_embedding.weight.copy_(torch.from_numpy(pretrained_item_embeddings))

        self.position_embedding = nn.Embedding(max_len, hidden_dim)
        self.outcome_embedding = nn.Embedding(2, hidden_dim) if use_outcome_embedding else None
        self.dropout = nn.Dropout(dropout)
        self.layer_norm = nn.LayerNorm(hidden_dim)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=num_heads,
            dim_feedforward=hidden_dim * 4,
            dropout=dropout,
            batch_first=True,
            activation="gelu",
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_blocks)

    def encode(self, input_items, input_outcomes):
        batch_size, seq_len = input_items.shape
        position_ids = torch.arange(seq_len, device=input_items.device).unsqueeze(0).expand(batch_size, seq_len)

        x = self.item_embedding(input_items) + self.position_embedding(position_ids)
        if self.outcome_embedding is not None:
            x = x + self.outcome_embedding(input_outcomes.clamp(min=0, max=1))
        x = self.layer_norm(self.dropout(x))

        padding_mask = input_items.eq(0)
        causal_mask = torch.triu(
            torch.ones(seq_len, seq_len, device=input_items.device, dtype=torch.bool),
            diagonal=1,
        )
        hidden = self.encoder(x, mask=causal_mask, src_key_padding_mask=padding_mask)
        return hidden

    def forward(self, input_items, input_outcomes, pos_targets, neg_targets):
        hidden = self.encode(input_items, input_outcomes)
        pos_emb = self.item_embedding(pos_targets)
        neg_emb = self.item_embedding(neg_targets)

        pos_logits = (hidden * pos_emb).sum(dim=-1)
        neg_logits = (hidden * neg_emb).sum(dim=-1)
        return pos_logits, neg_logits

    def sequence_representation(self, input_items, input_outcomes):
        hidden = self.encode(input_items, input_outcomes)
        lengths = input_items.ne(0).sum(dim=1) - 1
        lengths = lengths.clamp(min=0)
        batch_indices = torch.arange(hidden.size(0), device=hidden.device)
        return hidden[batch_indices, lengths]


def bce_loss(pos_logits, neg_logits, pos_targets):
    mask = pos_targets.ne(0).float()
    pos_loss = -torch.log(torch.sigmoid(pos_logits).clamp(min=1e-8))
    neg_loss = -torch.log(torch.sigmoid(-neg_logits).clamp(min=1e-8))
    loss = ((pos_loss + neg_loss) * mask).sum() / mask.sum().clamp(min=1.0)
    return loss


def build_candidate_matrix(model, device):
    item_weights = model.item_embedding.weight.detach()[1:].to(device)
    normalized = torch.nn.functional.normalize(item_weights, p=2, dim=1)
    return normalized


def evaluate_sasrec(model, examples, k_values, max_len, num_items, device):
    model.eval()
    metrics = {k: {"HR": 0.0, "NDCG": 0.0} for k in k_values}
    candidate_matrix = build_candidate_matrix(model, device)
    evaluated = 0

    with torch.no_grad():
        for example in examples:
            history_items = example["history_items"]
            history_outcomes = example["history_outcomes"]
            target_item = example["target_item"]

            if not history_items:
                continue

            input_items = torch.tensor(
                [pad_left(history_items, max_len, 0)],
                dtype=torch.long,
                device=device,
            )
            input_outcomes = torch.tensor(
                [pad_left(history_outcomes, max_len, 0)],
                dtype=torch.long,
                device=device,
            )

            user_repr = model.sequence_representation(input_items, input_outcomes)
            user_repr = torch.nn.functional.normalize(user_repr, p=2, dim=1)
            scores = torch.matmul(user_repr, candidate_matrix.transpose(0, 1)).squeeze(0)

            seen = set(history_items)
            for item_idx in seen:
                if item_idx > 0:
                    scores[item_idx - 1] = -1e9

            ranking = torch.argsort(scores, descending=True)
            ranked_items = [int(idx.item()) + 1 for idx in ranking[: max(k_values)]]

            for k in k_values:
                metrics[k]["HR"] += 1.0 if target_item in ranked_items[:k] else 0.0
                metrics[k]["NDCG"] += compute_ndcg(target_item, ranked_items, k)
            evaluated += 1

    for k in k_values:
        metrics[k]["HR"] /= max(evaluated, 1)
        metrics[k]["NDCG"] /= max(evaluated, 1)
    return metrics, evaluated


def compute_ndcg(target_item, ranked_items, k):
    try:
        rank = ranked_items[:k].index(target_item)
    except ValueError:
        return 0.0
    return 1.0 / math.log(rank + 2, 2)


def ensure_dir(path):
    if not os.path.isdir(path):
        os.makedirs(path)


def save_metrics(path, payload):
    with open(path, "wt", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def main():
    args = parse_args()
    set_seed(args.seed)

    device = torch.device(args.device or ("cuda" if torch.cuda.is_available() else "cpu"))
    k_values = [int(value) for value in args.k_values.split(",") if value.strip()]

    train_rows = load_jsonl(args.train_path)
    validation_rows = load_jsonl(args.validation_path)
    test_rows = load_jsonl(args.test_path)
    item_to_index, index_to_item = load_item_lookup(args.items_path)
    num_items = len(index_to_item) - 1

    pretrained_matrix = None
    hidden_dim = args.hidden_dim
    if args.use_pretrained_embeddings:
        pretrained_matrix = load_pretrained_embeddings(
            args.embeddings_path,
            args.items_path,
            item_to_index,
        )
        hidden_dim = pretrained_matrix.shape[1]

    train_sequences, validation_examples, test_examples = build_split_sequences(
        train_rows=train_rows,
        validation_rows=validation_rows,
        test_rows=test_rows,
        item_to_index=item_to_index,
    )

    train_dataset = SASRecTrainDataset(
        train_sequences=train_sequences,
        max_len=args.max_len,
        num_items=num_items,
    )
    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
    )

    model = SASRecModel(
        num_items=num_items,
        hidden_dim=hidden_dim,
        max_len=args.max_len,
        num_blocks=args.num_blocks,
        num_heads=args.num_heads,
        dropout=args.dropout,
        pretrained_item_embeddings=pretrained_matrix,
        use_outcome_embedding=args.use_outcome_embedding,
    ).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    best_validation_score = -1.0
    best_validation_metrics = None
    best_epoch = 0
    epochs_without_improvement = 0
    best_state = None
    history = []

    print("Device:", device)
    print("Training users:", len(train_sequences))
    print("Training sequences:", len(train_dataset))
    print("Validation users:", len(validation_examples))
    print("Test users:", len(test_examples))
    print("Items:", num_items)
    print("Hidden dim:", hidden_dim)

    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        total_batches = 0

        for batch in train_loader:
            input_items = batch["input_items"].to(device)
            input_outcomes = batch["input_outcomes"].to(device)
            pos_targets = batch["pos_targets"].to(device)
            neg_targets = batch["neg_targets"].to(device)

            optimizer.zero_grad()
            pos_logits, neg_logits = model(
                input_items=input_items,
                input_outcomes=input_outcomes,
                pos_targets=pos_targets,
                neg_targets=neg_targets,
            )
            loss = bce_loss(pos_logits, neg_logits, pos_targets)
            loss.backward()
            optimizer.step()

            total_loss += float(loss.item())
            total_batches += 1

        validation_metrics, evaluated_val = evaluate_sasrec(
            model=model,
            examples=validation_examples,
            k_values=k_values,
            max_len=args.max_len,
            num_items=num_items,
            device=device,
        )

        epoch_result = {
            "epoch": epoch,
            "train_loss": total_loss / max(total_batches, 1),
            "validation_metrics": validation_metrics,
            "evaluated_validation_users": evaluated_val,
        }
        history.append(epoch_result)

        primary_k = max(k_values)
        primary_score = validation_metrics[primary_k][args.monitor_metric]
        print(
            "Epoch %d/%d\tloss=%.4f\tval_HR@%d=%.4f\tval_NDCG@%d=%.4f"
            % (
                epoch,
                args.epochs,
                epoch_result["train_loss"],
                primary_k,
                validation_metrics[primary_k]["HR"],
                primary_k,
                validation_metrics[primary_k]["NDCG"],
            )
        )

        if primary_score > best_validation_score:
            best_validation_score = primary_score
            best_validation_metrics = validation_metrics
            best_epoch = epoch
            epochs_without_improvement = 0
            best_state = {key: value.detach().cpu() for key, value in model.state_dict().items()}
        else:
            epochs_without_improvement += 1
            if args.early_stop_patience > 0 and epochs_without_improvement >= args.early_stop_patience:
                print(
                    "Early stopping after epoch %d with best epoch %d based on %s@%d."
                    % (epoch, best_epoch, args.monitor_metric, primary_k)
                )
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    test_metrics, evaluated_test = evaluate_sasrec(
        model=model,
        examples=test_examples,
        k_values=k_values,
        max_len=args.max_len,
        num_items=num_items,
        device=device,
    )

    ensure_dir(args.save_dir)
    checkpoint_path = os.path.join(args.save_dir, "sasrec_model.pt")
    metrics_path = os.path.join(args.save_dir, "sasrec_metrics.json")
    torch.save(model.state_dict(), checkpoint_path)
    save_metrics(
        metrics_path,
        {
            "config": vars(args),
            "history": history,
            "best_epoch": best_epoch,
            "best_validation_score": best_validation_score,
            "best_validation_metrics": best_validation_metrics,
            "test_metrics": test_metrics,
            "evaluated_test_users": evaluated_test,
        },
    )

    print(
        "\nBest epoch=%d\tbest %s@%d=%.4f"
        % (best_epoch, args.monitor_metric, max(k_values), best_validation_score)
    )
    for k in k_values:
        print(
            "Test HR@%d=%.4f\tNDCG@%d=%.4f"
            % (k, test_metrics[k]["HR"], k, test_metrics[k]["NDCG"])
        )
    print("Saved model to", checkpoint_path)
    print("Saved metrics to", metrics_path)


if __name__ == "__main__":
    main()
